exclude_patterns:
  - "**/**/tests__/"
  - "**/**/migrations/**"
  - "utility/*"
  - "**/**/urls.py"
  - "**/**/**/serializers/serializer*"
  - "**/**/**/viewsets.py"
  - "config/settings/*"
  - "**/**/admin.py"
  - "**/**/models/__init__.py"
